AllCops:
  NewCops: enable
  Exclude:
    - "test/dummy/**/*"
  TargetRubyVersion: 2.6

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
